#!/usr/bin/env node
// Downloads the catalogue into public/fonts and writes the @font-face rules
// that name them. Run after adding an entry to src/slice/fonts/catalog.ts:
//
//   node scripts/fonts.mjs [id ...]
//
// One .ttf per face rather than the WOFF2 Google serves a browser: opentype.js
// cannot read WOFF2 without a Brotli decompressor, and outline mode has to parse
// the same binary the stylesheet paints from.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const fontDir = join(root, 'public', 'fonts')
const licenseDir = join(fontDir, 'licenses')
const cssPath = join(root, 'src', 'wheel', 'fonts.css')

/** The catalogue, read as source: this script must not need the app to build. */
async function readCatalog() {
  const source = await readFile(join(root, 'src', 'slice', 'fonts', 'catalog.ts'), 'utf8')
  const entries = [...source.matchAll(/entry\(\{([\s\S]*?)\}\)/g)].map((match) => {
    const read = (key) => match[1].match(new RegExp(`${key}:\\s*'([^']*)'`))?.[1]
    return { id: read('id'), name: read('name'), family: read('family'), google: read('google') }
  })
  return entries
    .filter((font) => font.id)
    .map((font) => ({ ...font, google: font.google ?? font.family }))
}

async function fetchText(url, headers = {}) {
  const response = await fetch(url, { headers })
  if (!response.ok) throw new Error(`${response.status} ${url}`)
  return response.text()
}

/**
 * No browser user-agent, which is what makes the API answer with one truetype
 * file for the whole charset instead of a stack of unicode-range WOFF2 subsets.
 */
async function ttfUrl(google) {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(google)}`,
  )
  const url = css.match(/https:\/\/[^)]*\.ttf/)?.[0]
  if (!url) throw new Error(`no truetype source for ${google}`)
  return url
}

async function download(url, path) {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${response.status} ${url}`)
  const bytes = new Uint8Array(await response.arrayBuffer())
  await writeFile(path, bytes)
  return bytes.length
}

/** OFL, with the two other trees Google files a family under as fallbacks. */
async function license(id, google) {
  const slug = google.toLowerCase().replaceAll(' ', '')
  for (const tree of ['ofl', 'apache', 'ufl']) {
    const name = tree === 'apache' ? 'LICENSE.txt' : tree === 'ufl' ? 'UFL.txt' : 'OFL.txt'
    const url = `https://raw.githubusercontent.com/google/fonts/main/${tree}/${slug}/${name}`
    const response = await fetch(url)
    if (response.ok) {
      await writeFile(join(licenseDir, `${id}.txt`), await response.text())
      return tree
    }
  }
  throw new Error(`no license found for ${google}`)
}

function stylesheet(fonts) {
  const rules = fonts
    .map((font) =>
      [
        '@font-face {',
        `  font-family: "${font.family}";`,
        '  font-style: normal;',
        '  font-weight: 400;',
        '  font-display: swap;',
        `  src: url("/fonts/${font.id}.ttf") format("truetype");`,
        '}',
      ].join('\n'),
    )
    .join('\n\n')

  return `/* Generated by scripts/fonts.mjs. Do not edit — add a catalogue entry and rerun.

   Self-hosted rather than fetched from a font CDN: the wheel has to keep setting
   type when a third party is unreachable, and outline mode parses the same binary
   this stylesheet paints from. One file per face, whole charset, no unicode-range
   split — the parser needs the glyphs a subset would have dropped. */

${rules}
`
}

const wanted = process.argv.slice(2)
const catalog = await readCatalog()
const fonts = wanted.length > 0 ? catalog.filter((font) => wanted.includes(font.id)) : catalog

await mkdir(licenseDir, { recursive: true })

let total = 0
for (const [index, font] of fonts.entries()) {
  const position = `${index + 1}/${fonts.length}`
  try {
    const url = await ttfUrl(font.google)
    const bytes = await download(url, join(fontDir, `${font.id}.ttf`))
    const tree = await license(font.id, font.google)
    total += bytes
    console.log(`${position} ${font.id} ${(bytes / 1024).toFixed(0)}KB ${tree}`)
  } catch (error) {
    console.log(`${position} ${font.id} FAILED ${error.message}`)
    process.exitCode = 1
  }
}

await writeFile(cssPath, stylesheet(catalog))
console.log(`${fonts.length} faces, ${(total / 1024 / 1024).toFixed(1)}MB, wrote ${cssPath}`)
