#!/usr/bin/env node
// Bakes one short run per face into src/slice/fonts/specimens.ts, so the picker
// can show a face without loading it. Run after scripts/fonts.mjs:
//
//   node scripts/specimens.mjs
//
// A specimen is a picture, not a source of metrics: nothing measures it and no
// wedge is fitted from it, so a stale one shows a slightly wrong preview rather
// than setting a name two different ways.

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import opentype from 'opentype.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(root, 'src', 'slice', 'fonts', 'specimens.ts')

/**
 * Nine glyphs, none repeated, grouped letters then figures. A wheel sets names
 * and it sets money, so a specimen has to answer both. `e` and `z` carry the
 * horizontals that a high-contrast face thins to hairlines — the first thing to
 * disappear on a narrow wedge — and `0` shows the stress axis those horizontals
 * belong to. A word would spend this width repeating a letter instead.
 */
const SPECIMEN = 'Ragez 850$'
/** The height every specimen is normalised to, so the picker's rows line up. */
export const HEIGHT = 24

async function readCatalog() {
  const source = await readFile(join(root, 'src', 'slice', 'fonts', 'catalog.ts'), 'utf8')
  return [...source.matchAll(/entry\(\{([\s\S]*?)\}\)/g)]
    .map((match) => match[1].match(/id:\s*'([^']*)'/)?.[1])
    .filter(Boolean)
}

const round = (n) => Math.round(n * 10) / 10

/**
 * Glyph by glyph rather than through `font.getPath`, which runs the shaper and
 * throws on lookup types opentype.js does not implement — Oswald's, for one.
 * It is also what outline mode does at runtime, so a specimen shows the same
 * letterforms a wedge will.
 */
function runPath(font, size) {
  const path = new opentype.Path()
  let x = 0
  for (const char of SPECIMEN) {
    const glyph = font.charToGlyph(char)
    path.extend(glyph.getPath(x, 0, size))
    x += ((glyph.advanceWidth ?? 0) * size) / font.unitsPerEm
  }
  return path
}

/**
 * Normalised on the ink the word actually leaves, not on a declared cap height:
 * Rye reports one four times off, and a specimen that trusted it baked at four
 * times the size of its neighbours. The word carries an ascender and no
 * descender, so its ink is the same feature in every face.
 */
function specimen(font) {
  const trial = runPath(font, 100).getBoundingBox()
  const inked = trial.y2 - trial.y1
  const size = inked > 0 ? (100 * HEIGHT) / inked : HEIGHT
  const path = runPath(font, size)
  const box = path.getBoundingBox()

  const commands = path.commands.map((command) => {
    const shift = (x, y) => `${round(x - box.x1)} ${round(y - box.y1)}`
    switch (command.type) {
      case 'M':
        return `M${shift(command.x, command.y)}`
      case 'L':
        return `L${shift(command.x, command.y)}`
      case 'Q':
        return `Q${shift(command.x1, command.y1)} ${shift(command.x, command.y)}`
      case 'C':
        return `C${shift(command.x1, command.y1)} ${shift(command.x2, command.y2)} ${shift(command.x, command.y)}`
      default:
        return 'Z'
    }
  })

  return { d: commands.join(''), width: round(box.x2 - box.x1), height: round(box.y2 - box.y1) }
}

const ids = await readCatalog()
const baked = []

for (const [index, id] of ids.entries()) {
  const bytes = await readFile(join(root, 'public', 'fonts', `${id}.ttf`))
  const font = opentype.parse(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.length))
  const { d, width, height } = specimen(font)
  baked.push(`  '${id}': { d: '${d}', width: ${width}, height: ${height} },`)
  console.log(`${index + 1}/${ids.length} ${id} ${(d.length / 1024).toFixed(1)}KB`)
}

const module = `// Generated by scripts/specimens.mjs. Do not edit — rerun it after adding a face.
//
// One short run per face, baked to outlines so the picker can show every face
// without loading any of them. A picture, not a source of metrics.

export type Specimen = { d: string; width: number; height: number }

/** What every specimen is normalised to, cap height rather than em box. */
export const SPECIMEN_HEIGHT = ${HEIGHT}

export const SPECIMENS: Record<string, Specimen> = {
${baked.join('\n')}
}
`

await writeFile(outPath, module)
console.log(`${ids.length} specimens, ${(module.length / 1024).toFixed(0)}KB, wrote ${outPath}`)
